# xnat/local.yaml

# unique name for the VM
name: xnat-war

# email address for server admin
admin: admin@yourorg.org

# FQDN or IP address of mail server that will handle outgoing messages
smtp:  mail.server

# unique IP address for the VM
vm_ip: 10.1.101.170

# You can override the URL settings to download from another source, e.g. a build server.
# xnat_url:     https://jenkins.xnat.org/job/XNAT%20Web/lastSuccessfulBuild/artifact/build/libs/xnat-web-1.7.0-SNAPSHOT.war
# pipeline_url: https://jenkins.xnat.org/job/XNAT%20Pipeline/lastSuccessfulBuild/artifact/build/libs/xnat-pipeline-1.7.0-SNAPSHOT.zip

# specify additional shares in a 'shares' property

# shares:
#   './shared':                      # path to local folder on host
#     - '/shared'                    # path to folder in VM
#     - ['fmode=777','dmode=777']    # (optional) 'mount_options' array
